language: node_js

node_js: 
    - "8.15.0"

install: 
    - npm install && npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: origin.thiss.io
    branch: master
    repo: origin.thiss.io
    on:
       all_branches: true
       condition: $TRAVIS_TAG =~ ^release- && $TRAVIS_BRANCH =~ ^production$
